name: Run Python Script
on:
  push:
    paths:
    - 'styles/'
jobs:
  replace:
    name: create files
    runs-on: ubuntu-latest
    steps:
    - name: Check-out
      uses: actions/checkout@v3
    - name: run
      run: |
        sudo apt-get install texlive texlive-base texlive-luatex
        python replace.py
        cat test*.tex
