name: Run Python Script
on:
  push:
#    paths:
#    - 'example.bib'
jobs:
  replace:
    name: create files
    runs-on: ubuntu-latest
    steps:
    - name: Check-out
      uses: actions/checkout@v3
    - name: Compile Latex Document
      uses: xu-cheng/latex-action@v2
    - name: run
      run: |
        python replace.py
        
