name: Run Python Script
on:
  push:
    paths:
    - 'example.bib'
jobs:
  replace:
    name: replace
    runs-on: ubuntu-latest
    steps:
    - name: replace
      run: python replace.py
      shell: sh
