name: Build BiBTeX document
on: 
  push:
    paths:
    - 'example.bib'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ./tests/bibtex_test.tex
          latexmk_use_lualatex : true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: BiBTeX
          path: bibtex_test.pdf
