name: Run Python Script

on:
  push:
    paths:
    - 'example.bib'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          root_file: ./replace.py
          python-version: 3.8
      - name: Run Python script
        run: |
         python3 replace.py
