name: Run Python Script
on:
  push:
#    paths:
#    - 'example.bib'
jobs:
  replace:
    name: replace
    runs-on: ubuntu-latest
    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: run
      run: |
        python replace.py
        ls *.tex
        cat test*.tex
        for ((i=0; i < 2; i++)) do latex test$i.tex; done
