name: Run Python Script
on:
  push:
#    paths:
#    - 'example.bib'
jobs:
  replace:
    name: create files
    runs-on: ubuntu-latest
    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: run
      run: |
        python replace.py
        for ((i=0; i < 2; i++)) do pdflatex test$i.tex done
      #  ls *.tex
      #  cat test*.tex

          
        
