name: Run Python Script
on:
  push:
#    paths:
#    - 'example.bib'
jobs:
  replace:
    name: create files
    runs-on: ubuntu-latest
    steps:
    - name: Check-out
      uses: actions/checkout@v3
    - name: run
      run: |
        python replace.py
      #  ls *.tex
      #  cat test*.tex
    - name: compile
      uses: xu-cheng/latex-action@v2
      with:
        root_file: (for (i = 0 ; i < 1 ; i++) {
          test$i.tex
          }

        
