name: Run Python Script
on:
  push:
#    paths:
#    - 'example.bib'
jobs:
  replace:
    name: create files
    runs-on: ubuntu-latest
    steps:
    - name: Check-out
      uses: actions/checkout@v3
    - name: run
      run: |
        python replace.py
    - name: compile
      uses: xu-cheng/latex-action@v2
      with:
          root_file: test0.tex
    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: test
        path: test0.tex
        
