name: Run Python Script
on:
  push:
#    paths:
#    - 'example.bib'
jobs:
  replace:
    name: create files
    runs-on: ubuntu-latest
    steps:
    - name: Check-out
      uses: actions/checkout@v3
    - name: run
      run: |
        python replace.py
      #  ls *.tex
      #  cat test*.tex
    - name: compile
      uses: xu-cheng/latex-action@v2
    - name: compile
      run: |
        for ((i=0;i<1;i++))
        do
        pdflatex test$i.tex
        done
        
